# Generated by Django 4.1 on 2023-04-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_relative_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
